menu:
  Home: /
  categories: /c
  tags: /t

sitename: LERNB
sitedomain: https://lernb.com
siteadmin: lernb.com
siteemail: lernb@qq.com
servername: Tencent
serverwebsite: https://cloud.tencent.com/
siteICP: 苏ICP备2020049244号

notice: 

uname: ler
title: LERNB | 网络日志
description: LERNB - 学习、记录、分享 - LERNB
keywords: LERNB,技术,分享,博客,IT新闻,互联网,Internet,数码,科技,网络,科普,通信,智能手机,blog
favicon: https://gitee.com/lernb/pic-host/raw/master/img/20210724215606.png
headImg: https://gitee.com/lernb/pic-host/raw/master/img/20210724215740.png
userhead: https://gitee.com/lernb/pic-host/raw/master/img/20210724215544.jpg
bannerBg: https://gitee.com/lernb/pic-host/raw/master/img/20210724215518.jpg

# 侧栏插件
showAuthor: false
showRecent: true
showTag: true
showArchive: false
showPostMenu: true
showCategory: true
showCount: true
showComment: true

headerRecent: false