menu:
  Home: /
  categories: /c
  tags: /t

sitename: LERNB
sitedomain: https://lernb.com
siteadmin: lernb.com
siteemail: lernb@qq.com
servername: Tencent
serverwebsite: https://cloud.tencent.com/
siteICP: 

notice: 

uname: ler
title: LERNB | 网络日志
description: LERNB - 个人网站，记录、分享
keywords: LERNB,技术,分享,博客,IT新闻,互联网,Internet,数码,科技,网络,科普,通信,智能手机,blog
favicon: /asset/u.jpg
headImg: /asset/lernb.png
userhead: /asset/u.jpg
bannerBg: /asset/typ3.jpg

# 侧栏插件
showAuthor: false
showRecent: true
showTag: true
showArchive: false
showPostMenu: true
showCategory: true
showCount: true

showComment: true

headerRecent: false